import com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar

buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }
    dependencies {
        classpath 'com.gradleup.shadow:shadow-gradle-plugin:9.4.1'
    }
}
plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'maven-publish'
    id 'java-library'
}

repositories {
    maven {
        name = 'Fabric'
        url = 'https://maven.fabricmc.net/'
    }
    mavenLocal()
    gradlePluginPortal()
}
apply plugin: 'com.gradleup.shadow'
configurations {
    shadowMe
    implementation.extendsFrom shadowMe
}
tasks.named('shadowJar', ShadowJar) {
    configurations = []
    from sourceSets.main.output
    from sourceSets.client.output
    from {
        project.configurations.shadowMe.collect { it.isDirectory() ? it : zipTree(it) }
    }
    archiveClassifier = 's'
    relocate 'net.johnseagull.figManager', "net.johnseagull.${project.archives_base_name}.libs.figManager"
    mergeServiceFiles()
}
version = project.mod_version
group = project.maven_group
base {
    archivesName = project.archives_base_name
}
loom {
    splitEnvironmentSourceSets()

    mods {
        "${project.archives_base_name}" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}
fabricApi {
    configureDataGeneration {
        client = true
    }
}
dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
    api "net.johnseagull:figmanager:${project.fig_version}"
}
processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version", project.minecraft_version
    inputs.property "loader_version", project.loader_version
    filteringCharset "UTF-8"
    filesMatching("fabric.mod.json") {
        expand "version": project.version,
                "minecraft_version": project.minecraft_version,
                "loader_version": project.loader_version
    }
}
java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
    withSourcesJar()
}

tasks.withType(JavaCompile).configureEach {
    it.options.encoding = "UTF-8"
}
jar {
    from("LICENSE") {
        rename { "${it}_${project.archives_base_name}" }
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            artifactId = project.archives_base_name
            from components.java
        }
    }
}
